require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 2.7

Metrics/LineLength:
  Enabled: false
  Exclude:
    - 'bin/*'

Metrics/PerceivedComplexity:
  Enabled: false
  Exclude:
    - 'bin/*'
